# Generated by Django 4.2.5 on 2023-11-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_task_completion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_completed',
            new_name='due_date',
        ),
    ]
