# Generated by Django 4.2.5 on 2023-11-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_repetitionpattern_task_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetitionpattern',
            name='frequency',
            field=models.CharField(choices=[('day(s)', 'Day(s)'), ('week(s)', 'Week(s)'), ('month(s)', 'Month(s)')], max_length=20),
        ),
    ]
