# Generated by Django 4.2.5 on 2023-11-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_rename_interval_repetitionpattern_day_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To Do'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
    ]
