# Generated by Django 4.2.5 on 2023-11-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
